use paymentdb;

CREATE TABLE Login(	
email VARCHAR(30) DEFAULT NULL,
phoneno VARCHAR(30) DEFAULT NULL,
SSN CHAR(9) NOT NULL,
CONSTRAINT LPK
PRIMARY KEY (SSN)
);

CREATE TABLE Bank_Account(
BankID VARCHAR(30) NOT NULL,
BANumber VARCHAR(30) NOT NULL,
CONSTRAINT BAPK
PRIMARY KEY (BankID, BANumber)
);

CREATE TABLE User_Account(
SSN CHAR(9) NOT NULL,
Name VARCHAR(30) DEFAULT NULL,
email VARCHAR(30) DEFAULT NULL,
phoneno	VARCHAR(30) DEFAULT NULL,
Balance VARCHAR(30) DEFAULT NULL,
BankID VARCHAR(30) DEFAULT NULL,
BANumber VARCHAR(11) DEFAULT NULL,
PBAVerified CHAR(4) DEFAULT NULL,
CONSTRAINT UAPK
PRIMARY KEY (SSN),
CONSTRAINT UAFK
FOREIGN KEY (BankID, BANumber) REFERENCES Bank_Account(BankID, BANumber) 
ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Send_Transaction(
STid INT(30) NOT NULL AUTO_INCREMENT,
User VARCHAR(30) DEFAULT NULL,
Amount VARCHAR(11) DEFAULT NULL,
Date_Time DATE DEFAULT NULL,
SSN CHAR(9) DEFAULT NULL,
Memo VARCHAR(30) DEFAULT NULL,
Cancel_Reason VARCHAR(30) DEFAULT NULL,
CONSTRAINT STPK
PRIMARY KEY (STid),
CONSTRAINT STFK
FOREIGN KEY (SSN) REFERENCES User_Account (SSN) 
ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE Request_Transaction(
RTid INT(30) NOT NULL AUTO_INCREMENT,
User VARCHAR(30) DEFAULT NULL,
Amount VARCHAR(11) DEFAULT NULL,
Date_Time DATE DEFAULT NULL,
SSN CHAR(9) DEFAULT NULL,
Memo VARCHAR(30) DEFAULT NULL,
CONSTRAINT RTPK
PRIMARY KEY (RTid),
CONSTRAINT RTFK
FOREIGN KEY (SSN) REFERENCES User_Account (SSN)
 ON DELETE SET NULL ON UPDATE CASCADE
);



